# Generated by Django 5.1.6 on 2025-02-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/')),
                ('category', models.CharField(blank=True, choices=[('deforestation', 'Deforestation'), ('plastic_pollution', 'Plastic Pollution'), ('illegal_dumping', 'Illegal Dumping'), ('oil_spill', 'Oil Spill')], max_length=50, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
