# Generated by Django 5.1.6 on 2025-02-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='environmentalissue',
            name='address',
            field=models.TextField(default='Coimbatore'),
        ),
        migrations.AddField(
            model_name='environmentalissue',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default='11.061180', max_digits=9),
        ),
        migrations.AddField(
            model_name='environmentalissue',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default='77.034660', max_digits=9),
        ),
        migrations.AlterField(
            model_name='environmentalissue',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
