# Generated by Django 5.1.6 on 2025-02-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalissue',
            name='category',
        ),
        migrations.RemoveField(
            model_name='environmentalissue',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='environmentalissue',
            name='reported_at',
        ),
        migrations.AddField(
            model_name='environmentalissue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalissue',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
