# Generated by Django 5.1.6 on 2025-02-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_environmentalissue_category_and_more'),
    ]

    operations = [
    ]
